#!/usr/bin/env bash
# create a script that display A domain record info

display_records () {
	domain="$1"
	subdomains="$2"
	if [ -z "$subdomains" ]
	then
		subdomains="www lb-01 web-01 web-02"
	fi
	for subdomain in $subdomains
	do
		addr=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $NF}' | tail -n1)
		echo "The subdomain $subdomain is a A record and points to $addr"
	done
}

if [ $# -gt 0 ]; then
	display_records "$1" "$2"
fi
