#!/usr/bin/env bash
# Transfer files from client to a server:
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    src_path=$1
	ip=$2
	username=$3
	if [ "$4" ]; then
		ssh_path=$4
		scp -i "${ssh_path}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${src_path}" "${username}@${ip}:${ssh_path}"
	else
		scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${src_path}" "${username}@${ip}:${ssh_path}"
	fi
fi

