#!/usr/bin/env bash
# install nginx and serve a simple page.
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
to_replace="location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sed -i "s@# pass PHP scripts to FastCGI server@$to_replace@" /etc/nginx/sites-available/default
service nginx restart
