#!/usr/bin/env bash
# install nginx and serve a simple page.
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
# shellcheck disable=SC2154
echo '# My server configuration for ALX
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html

	server_name $HOSTNAME;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	add_header X-Served-By $HOSTNAME;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;

	location = /404.html {
		root /var/www/html;
		internal;
	}
}
' > /etc/nginx/sites-available/default
service nginx restart

