#!/usr/bin/env bash
# debug a server
apt-get update
apt-get install -y nginx
sed -i 's/^listen \[::\]:80/# &/' /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
