#!/usr/bin/env bash
# debug a server
sed -i 's/^listen \[::\]:80/# &/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
