#!/usr/bin/env bash
#  fizz buzz problem using bask
counter=1
while [ $counter -le 100 ]; do
	if [ $(( counter % 3 )) -eq 0 ] && [ $(( counter % 5 )) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $(( counter % 3 )) -eq 0 ]; then
		echo "Fizz"
	elif [ $(( counter % 5 )) -eq 0 ]; then
		echo "Buzz"
	else
		echo $counter
	fi
	((counter+=1))
done
