#!/usr/bin/env bash
#  displays Best School 10 times
counter=1
while [ $counter -le 20 ]; do
	echo $counter
	if [ $counter -eq 4 ]; then
		echo "bad luck from China"
	elif [ $counter -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((counter+=1))
done
