#!/usr/bin/env bash
#  displays hours from 0 to 12 and minutes from 1 to 59
hour=0
while [ $hour -lt 13 ]; do
	echo "Hour:" $hour
	minutes=1
	while [ $minutes -lt 60 ]; do
		echo $minutes
		((minutes+=1))
	done
	((hour+=1))
done
