#!/usr/bin/env bash
#  print info about 'school' file
file="./school"
if [ -f "$file" ] || [ -d "$file" ]; then
	echo "school file exists"
	if [ ! -s "$file" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ]; then
		echo "school file is regular file"
	fi
else
	echo "school file does not exist"
fi
