#!/usr/bin/env bash
# config nginx to be executed using nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
